apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: itxa-nfs-claim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: ibmc-file-gold
  volumeName: itxa-pv
  volumeMode: Filesystem
