# Source: ibm-itxa-prod/templates/itxa-hpa.yaml
# Licensed Materials - Property of IBM
# IBM Order Management Software (5725-D10)
# (C) Copyright IBM Corp. 2018, 2020 All Rights Reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.true

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: tools
  name: release-name-ibm-itxa-prod-itxa-hpa
  labels:
    app.kubernetes.io/name: "release-name-ibm-itxa-prod"
    helm.sh/chart: "ibm-itxa-prod"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/instance: "release-name"
    release: "release-name" 
spec:
  maxReplicas: 4
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: release-name-ibm-itxa-prod-itxauiserver
  targetCPUUtilizationPercentage: 25